import { useState } from "react";
import PageHeader from "../../components/common/PageHeader";
import { useAuth } from "../../auth/AuthContext";
import { facultyApi } from "../../services/api";
import useAsyncData from "../../hooks/useAsyncData";

export default function FacultyReportsPage() {
  const { currentUser } = useAuth();
  const [report, setReport] = useState("individual");
  const { data, loading, error, setData } = useAsyncData(
    () => facultyApi.reports(currentUser.id),
    [currentUser.id]
  );
  const rows = Array.isArray(data) ? data : [];

  const exportLatestReport = async () => {
    const candidates = rows.filter((r) => r.type === report && r.status === "completed");
    if (candidates.length === 0) {
      alert("No completed reports available for this type yet.");
      return;
    }
    const latest = candidates[0];
    const data = await facultyApi.reportData(currentUser.id, latest.reportId);
    const win = window.open("", "_blank");
    if (!win) {
      alert("Popup blocked. Please allow popups to export the report.");
      return;
    }
    const prettyType = data.type ? data.type.charAt(0).toUpperCase() + data.type.slice(1) : "Report";
    const generatedAt = data.generatedAt ? new Date(data.generatedAt).toLocaleString() : "N/A";

    const rowsHtml = (data.rows || [])
      .map(
        (r) => `<tr>
          <td>${r.studentId || "-"}</td>
          <td>${r.name || "-"}</td>
          <td>${r.rollNumber || "-"}</td>
          <td>${r.phone || "-"}</td>
          <td>${r.semester ?? "-"}</td>
          <td>${r.attendancePercent ?? 0}%</td>
          <td>${r.presentDays ?? 0}</td>
          <td>${r.absentDays ?? 0}</td>
        </tr>`
      )
      .join("");

    win.document.write(`<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>${latest.reportId || "Report"}</title>
    <style>
      body { font-family: Arial, sans-serif; margin: 32px; color: #111; }
      h1 { margin: 0 0 8px; }
      .meta { margin: 4px 0; color: #444; }
      table { width: 100%; border-collapse: collapse; margin-top: 16px; }
      th, td { border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 13px; }
      th { background: #f3f3f3; }
      .footer { margin-top: 24px; font-size: 12px; color: #666; }
    </style>
  </head>
  <body>
    <h1>${prettyType} Attendance Report</h1>
    <div class="meta"><strong>Report ID:</strong> ${latest.reportId || "-"}</div>
    <div class="meta"><strong>Generated:</strong> ${generatedAt}</div>
    <div class="meta"><strong>Faculty ID:</strong> ${data.facultyId || "-"}</div>
    ${data.facultyName ? `<div class="meta"><strong>Faculty Name:</strong> ${data.facultyName}</div>` : ""}
    <table>
      <thead>
        <tr>
          <th>Student ID</th>
          <th>Student Name</th>
          <th>Roll No</th>
          <th>Phone</th>
          <th>Semester</th>
          <th>Attendance %</th>
          <th>Present Days</th>
          <th>Absent Days</th>
        </tr>
      </thead>
      <tbody>
        ${rowsHtml || "<tr><td colspan=\"8\">No data found.</td></tr>"}
      </tbody>
    </table>
    <div class="footer">Generated by Attendance System</div>
  </body>
</html>`);
    win.document.close();
    win.focus();
    win.print();
  };

  return (
    <div className="page-grid">
      <PageHeader title="Report Generator" subtitle="Generate and export attendance reports (PDF)" />
      <div className="card form-grid">
        <select value={report} onChange={(e) => setReport(e.target.value)}>
          <option value="individual">Individual Student Report</option>
          <option value="department">Department Report</option>
          <option value="semester">Semester Report</option>
        </select>
        <button
          onClick={async () => {
            const created = await facultyApi.createReport(currentUser.id, { type: report });
            setData([created, ...rows]);
          }}
        >
          Generate Report
        </button>
        <button onClick={exportLatestReport}>Export PDF</button>
      </div>
      {loading && <div className="card">Loading reports...</div>}
      {error && <div className="card error-text">{error}</div>}
      <div className="card">
        <ul className="simple-list">
          {rows.map((r) => (
            <li key={r._id || r.reportId}>
              {`${r.reportId} | ${r.type} | ${r.status}${r.generatedAt ? ` | ${new Date(r.generatedAt).toLocaleDateString()}` : ""}`}
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
